kind: ConfigMap
apiVersion: v1
metadata:
  name: quarkus-server-mtls
data:
  application.properties: |
    quarkus.http.ssl.certificate.key-store-file=/deployments/tls/server.keystore
    quarkus.http.ssl.certificate.key-store-password=password
    quarkus.http.ssl.certificate.trust-store-file=/deployments/tls/ca/truststore
    quarkus.http.ssl.certificate.trust-store-password=password

---

kind: Deployment
apiVersion: apps/v1
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      volumes:
        - name: server
          secret:
            secretName: quarkus-server-mtls
        - name: truststore
          secret:
            secretName: quarkus-truststore-mtls
        - name: config
          configMap:
              name: quarkus-server-mtls
      containers:
        - name: server
          image: 'image-registry.openshift-image-registry.svc:5000/prsrpi-0000-dev/server:latest'
          ports:
            - containerPort: 8443
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: 1m
              memory: 50Mi
          volumeMounts:
            - name: server
              readOnly: true
              mountPath: /deployments/tls
            - name: truststore
              readOnly: true
              mountPath: /deployments/tls/ca
            - name: config
              mountPath: /deployments/config
  revisionHistoryLimit: 2
---

apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443